### ISSUE TITLE
Beast companions loosing Dodge and Distract

### ISSUE THREAD

**Issue by Gyrofalcon** [ZerdBG3/RAW#145]
Ranger - Beast Master at level 7 gets [Exceptional Training](https://bg3.wiki/wiki/Beast_Master#Level_7).
After the animal got Dash, Disengage and Help as bonus action, it lost the Dodge and Distract from RAW.

**Comment by FelipeRenault** [comment]
Documenting for later: probably just needs to change the SpellSet for the companion:
```
new spellset "RangerCompanion_ExceptionalTraining"
add spell "Shout_Dash_NPC"
add spell "Shout_Dash_BonusAction_NPC"
add spell "Projectile_Jump"
add spell "Shout_Hide"
add spell "Shout_Disengage"
add spell "Shout_Disengage_BonusAction"
add spell "Target_Help"
add spell "Target_Help_BonusAction"
```
