### ISSUE TITLE
Any chance to get the dodge action as a standalone mod?

### ISSUE THREAD

**Issue by Azzurite** [ZerdBG3/RAW#147]
If not, I fully understand :) I just like most of the stuff you removed/change that Larian did, I'd just like to have the Dodge action  and not all the other stuff.

**Comment by FelipeRenault** [comment]
Checkout Eric's mods https://www.nexusmods.com/baldursgate3/mods/606?tab=description&BH=0
There are a ton of standalone options, I think Dodge + Distract can be downloaded on their own

For my mod, I have no plans on making anything modular... _yet_
