### ISSUE TITLE
Add ability to configure mod

### ISSUE THREAD

**Issue by MilesBHuff** [ZerdBG3/RAW#178]
It would be nice if it were possible to configure which parts of the mod we want to enable.  For instance, the inconvenience of having to manually find and equip things in my inventory every time I want to change weapons, as well as having to rearrange my action bars each time, is enough to make me reticent to put up with this mod, which is unfortunate because I really like the idea of using a truer 5e ruleset.

If adding the ability to configure the mod is off the table, do you see any future in which you are able to make the game's built-in weapon switching work as per 5e?  I obviously agree that it's fairly silly to have shields provide AC when both hands are being used to hold a crossbow.

**Comment by FelipeRenault** [comment]
Well, the mod already is configurable, it's explicitly said on both the Features list and on the Nexus Mods page. On the [Features](https://github.com/ZerdBG3/RAW/blob/main/Features.md) page it specifies which options are customizable

Specifically for your grudge with the weapon sets, a tip is that you can put the weapons on the hotbar to ease the weapon switch. But if you still dislike it, you can turn it off

**Comment by MilesBHuff** [comment]
Oh.  I'm sorry I missed that, then.  Thank you for the quick and considered reply.
And nice idea about the hotbar -- thanks!
