### ISSUE TITLE
Translation: german

### ISSUE THREAD

**Issue by michalnh** [ZerdBG3/RAW#182]
Hi there,
i want so support this great project and add a german translation. How can i start here?
Can you make me copies of the english files and folders, that i can edit please?
Later ingame: how to switch/choose between the languages? 
Does this depend on the ingame language?
Thank you and best regards

**Comment by FelipeRenault** [comment]
As we've discussed and tested on Discord, it is possible to have different localization files on the same packed mod.
We just need to create a new file like `RAW/Localization/{{LANGUAGE}}/RAW.loca` and the game will read from the specified language when loading the game on a different official language
I'll close this issue once we merge the german localization file so we have a reference on how-to for future languages

**Comment by michalnh** [comment]
Done and transmitted to [FelipeRenault]
