### ISSUE TITLE
Concentration Failsafe

### ISSUE THREAD

**Issue by arnaudpourbaix** [ZerdBG3/RAW#195]
Let's say I have a concentration spell going. I can't cast any concentration spell, works as intended.
But if I end my concentration spell, I still can't cast in the same turn. I need to disable failsafe to cast a new one.

**Comment by FelipeRenault** [comment]
This behavior is explained here:
https://github.com/ZerdBG3/RAW/blob/main/Features.md#concentration-failsafe-%EF%B8%8F-concentration_failsafe

> Given the implementation, spells that are concentration but don't give the caster a status might result in the concentration spells being blocked even though the caster ended concentration manually (or timeout). Basically taking any action (even moving) will remove the blockage, but if nothing works, just untoggle the passive to remove the blockage.
