### ISSUE TITLE
[Suggestion] Rename mod to something more descriptive of the goal

### ISSUE THREAD

**Issue by gnufred** [ZerdBG3/RAW#54]
100% up to you, but I think this mod would benefit from having a title more descriptive of it's goal. Like: Official Rule set, Rule as Written, or Table Top rules, and so on.

The word "rebalancing" could mean anything. It could aim to make the game easier, more difficult, more challenging, etc. And DnD, well, I hope players know that BG3 is about DnD ;)

I think it would make it easier for D&D table top player to find this mod and benefit from it.

**Comment by FelipeRenault** [comment]
I might rename it to `RAW`, that looks like a good name

**Comment by arhu32** [comment]
There's a mod for Pathfinder: Kingmaker called "Closer to Tabletop" that did something similar. Succinct and to the point. Also, more understandable for outsiders. "RAW" sounds a bit too obscure and I didn't know what it meant until I read it up.

Great mods though, I really appreciate what you are doing. My first contact with 5e was Solasta and by extension I read up on BG3 only recently. Would indeed prefer if Larian made it closer to tabletop.

**Comment by FelipeRenault** [comment]
Done
