### ISSUE TITLE
Replace current attack icons with "Attack" option that has no effect/animation

### ISSUE THREAD

**Issue by TheRealDjmr** [ZerdBG3/RAW#91]
Currently, when applying special attacks, unique animations are tied to unique actions. This means that when converting these special actions to shouts/toggles, you lose the animation tied to that action.

For example, for Fighter maneuvers, you have to choose the attack as a special attack, and expend the Superiority Die on a hit, when you should be able to choose when to expend the Superiority Die when the attack hits. There isn't an option for the Superiority Die to be applied on an offhand attack. The "fix" to this is to have a shout effect/toggle that can be used before/after the attack hits - this is typically triggered then by a normal attack without a unique animation. The same logic applies to Smites and other "When you hit" effects.

I propose that instead, the current MainHandAttack is changed into nothing more than a blank placeholder effect, and based on the appropriate shout/toggle that has been applied, the relevant animation and attack takes effect via the "CastSpell" function. In theory, this means that players only need to toggle what attack they want to perform and the appropriate effect/animation is used. It will also provide greater control on "stacking" effects (For example, mixing Divine Smite with Smite spells, and Sneak Attack). A build that can achieve this in early access is a Zariel Tiefling (with Searing Smite) using Menacing Attack. For this possibility, we could have one attack that combines both animations and effects of Menacing Attack and Searing Smite.

Of course, a lot of this is theoretical and this assumes many things such as:

1. Limited use attack effects (such as Colossus Slayer) do not fire off as a "hit" for the blank attack (this also includes defensive effects firing too).
2. By having no animation in the blank attack, the code that decides which attack effect is going ahead is able to play the animation as normal.
3. Multiple animation effects can be added seamlessly.

Ultimately before this idea would get off the ground, a prototype would be required just to prove the concept is even possible.

(To be clear, I envisage the current attack UI would change to have one Attack option for melee, one offhand Attack option for two-weapon fighting/Unarmed Strike (Monk), one Attack option for ranged and one offhand Attack option for Crossbow Expert)

**Comment by FelipeRenault** [comment]
This can be done with interrupts now. I'll look what features specifically need to have an interrupt option on top of the action option, but it will be a different issue from this one
